/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_phash_AudioHash */

#ifndef _Included_org_phash_AudioHash
#define _Included_org_phash_AudioHash
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_phash_AudioHash
 * Method:    readAudio
 * Signature: (Ljava/lang/String;IFLorg/phash/AudioMetaData;)[F
 */
JNIEXPORT jfloatArray JNICALL Java_org_phash_AudioHash_readAudio
  (JNIEnv *, jclass, jstring, jint, jfloat, jobject);

/*
 * Class:     org_phash_AudioHash
 * Method:    audioHash
 * Signature: ([FII)Lorg/phash/AudioHashObject;
 */
JNIEXPORT jobject JNICALL Java_org_phash_AudioHash_audioHash
  (JNIEnv *, jclass, jfloatArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
